export interface StorageDriver {
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
  deletePrefix(prefix: string): Promise<void>;
  /** URL that grants read access until `expiresAt` (ms epoch). */
  signedUrl(key: string, expiresAt: number): Promise<string>;
}

/** Keys are generated by the app only; still, refuse anything that could escape a prefix. */
export function assertSafeKey(key: string) {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9/_.-]{0,400}$/.test(key) || key.includes("..") || key.includes("//")) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}
