#!/usr/bin/env python3
"""Download the OFL font families INVTRA uses and produce:
  - assets/fonts/*.ttf   (used by the server-side invitation image renderer)
  - public/fonts/*.woff2 (served to browsers)
  - src/lib/fonts/metrics.json (advance widths used by the SVG text layout engine)

Run: python3 scripts/fetch-fonts.py   (requires: pip install fonttools brotli)
"""
import json, os, re, urllib.request
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTF_DIR = os.path.join(ROOT, "assets", "fonts")
WOFF_DIR = os.path.join(ROOT, "public", "fonts")
METRICS = os.path.join(ROOT, "assets", "fonts", "metrics.json")

FAMILIES = {
    "Cormorant Garamond": ["300", "400", "500", "600", "i400", "i500"],
    "Jost": ["300", "400", "500", "600"],
    "Cinzel": ["400", "500", "600"],
    "Pinyon Script": ["400"],
    "Playfair Display": ["400", "500", "i400"],
    "Italiana": ["400"],
    "Amiri": ["400", "700"],
    "Aref Ruqaa": ["400", "700"],
    "Reem Kufi": ["400", "500", "600"],
    "IBM Plex Sans Arabic": ["300", "400", "500", "600"],
    "El Messiri": ["400", "500", "600"],
    "Quicksand": ["400", "500", "600", "700"],
    "Baloo Bhaijaan 2": ["400", "500", "600", "700"],
    # Extra typefaces for the names (the couple, the baby, the graduate…).
    "Great Vibes": ["400"],
    "Dancing Script": ["400", "600"],
    "Pacifico": ["400"],
    "Fredoka": ["400", "600"],
    "Marcellus": ["400"],
    "Lalezar": ["400"],
    "Rakkas": ["400"],
    "Marhey": ["400", "600"],
    "Lemonada": ["400", "600"],
    "Katibeh": ["400"],
}

def css_url(family, variants):
    has_italic = any(v.startswith("i") for v in variants)
    if has_italic:
        tuples = sorted((1 if v.startswith("i") else 0, int(v.lstrip("i"))) for v in variants)
        spec = "ital,wght@" + ";".join(f"{i},{w}" for i, w in tuples)
    else:
        spec = "wght@" + ";".join(sorted(variants, key=int))
    return f"https://fonts.googleapis.com/css2?family={family.replace(' ', '+')}:{spec}"

def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

def main():
    os.makedirs(TTF_DIR, exist_ok=True)
    os.makedirs(WOFF_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(METRICS), exist_ok=True)
    metrics = {}
    for family, variants in FAMILIES.items():
        css = urllib.request.urlopen(css_url(family, variants)).read().decode()
        for block in re.findall(r"@font-face\s*{([^}]*)}", css):
            style = re.search(r"font-style:\s*(\w+)", block).group(1)
            weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
            url = re.search(r"url\(([^)]+)\)", block).group(1)
            name = f"{slug(family)}-{weight}{'-italic' if style == 'italic' else ''}"
            ttf_path = os.path.join(TTF_DIR, name + ".ttf")
            if not os.path.exists(ttf_path):
                urllib.request.urlretrieve(url, ttf_path)
            font = TTFont(ttf_path)
            upm = font["head"].unitsPerEm
            cmap = font.getBestCmap()
            hmtx = font["hmtx"].metrics
            widths = {}
            for cp in list(range(32, 127)) + list(range(0x00C0, 0x0180)) + [0x2013, 0x2014, 0x2019, 0x201C, 0x201D, 0x2022, 0x00B7, 0x2026, 0x0026]:
                g = cmap.get(cp)
                if g and g in hmtx:
                    widths[chr(cp)] = round(hmtx[g][0] / upm, 4)
            arabic = [hmtx[cmap[cp]][0] / upm for cp in range(0x0621, 0x064B) if cp in cmap and cmap[cp] in hmtx]
            hhea = font["hhea"]
            metrics[name] = {
                "family": family,
                "weight": int(weight),
                "style": style,
                "ascent": round(hhea.ascent / upm, 4),
                "descent": round(-hhea.descent / upm, 4),
                "avg": round(sum(widths.values()) / max(len(widths), 1), 4),
                "arabicAvg": round(sum(arabic) / len(arabic), 4) if arabic else None,
                "widths": widths,
            }
            woff_path = os.path.join(WOFF_DIR, name + ".woff2")
            if not os.path.exists(woff_path):
                font.flavor = "woff2"
                font.save(woff_path)
            print("ok", name)
    with open(METRICS, "w") as f:
        json.dump(metrics, f, separators=(",", ":"), ensure_ascii=False)

if __name__ == "__main__":
    main()


# ── Compact TS module for the isomorphic text layout engine ─────────────────
# Arabic advance widths change with contextual shaping; these factors were
# calibrated against resvg's shaped output (conservative, ~90th percentile).
ARABIC_FACTORS = {"Amiri": 0.71, "Aref Ruqaa": 0.72, "Reem Kufi": 0.53, "IBM Plex Sans Arabic": 0.81, "El Messiri": 0.84, "Baloo Bhaijaan 2": 0.75, "Lalezar": 0.87, "Rakkas": 0.81, "Marhey": 0.89, "Lemonada": 0.86, "Katibeh": 0.8}

def write_ts_module():
    metrics = json.load(open(METRICS))
    lines = [
        "// Generated by scripts/fetch-fonts.py — font metrics for SVG text layout. Do not edit.",
        "export type FontMetrics = { a: number; d: number; avg: number; ar: number | null; w: number[] };",
        "/** Keyed by `${family}|${weight}|${style}`; w = advance widths (em) for ASCII 32..126. */",
        "export const FONT_METRICS: Record<string, FontMetrics> = {",
    ]
    for name, v in metrics.items():
        w = [v["widths"].get(chr(c), v["avg"]) for c in range(32, 127)]
        ar = round(v["arabicAvg"] * ARABIC_FACTORS.get(v["family"], 0.8), 4) if v["arabicAvg"] else None
        key = f'{v["family"]}|{v["weight"]}|{v["style"]}'
        lines.append(
            f'  "{key}": {{ a: {v["ascent"]}, d: {v["descent"]}, avg: {v["avg"]}, ar: {json.dumps(ar)}, w: [{",".join(f"{x:.3f}".rstrip("0").rstrip(".") for x in w)}] }},'
        )
    lines.append("};")
    with open(os.path.join(ROOT, "src", "lib", "fonts", "metrics.ts"), "w") as f:
        f.write("\n".join(lines) + "\n")

def write_font_css():
    metrics = json.load(open(METRICS))
    faces = []
    for name, v in metrics.items():
        faces.append(
            "@font-face {\n"
            f'  font-family: "{v["family"]}";\n'
            f"  font-style: {v['style']};\n"
            f"  font-weight: {v['weight']};\n"
            "  font-display: swap;\n"
            f'  src: url("/fonts/{name}.woff2") format("woff2");\n'
            "}"
        )
    with open(os.path.join(ROOT, "src", "app", "fonts.css"), "w") as f:
        f.write("/* Generated by scripts/fetch-fonts.py — self-hosted OFL fonts. */\n" + "\n".join(faces) + "\n")

if __name__ == "__main__":
    write_ts_module()
    write_font_css()
