#!/usr/bin/env python3
"""Vectorise the supplied raster logo ("invtra logo.png") into crisp SVGs + icons.
Run: python3 scripts/vectorize-logo.py   (requires: pip install pillow potracer numpy)
"""
import os
import numpy as np
import potrace
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "invtra logo.png")
OUT = os.path.join(ROOT, "public", "brand")
COLOR = "#84664A"

src = Image.open(SRC).convert("RGBA")
im = Image.alpha_composite(Image.new("RGBA", src.size, (255, 255, 255, 255)), src)
a = np.array(im).astype(int)
dark = 255 * 3 - (a[:, :, 0] + a[:, :, 1] + a[:, :, 2])

BANDS = {
    "mark": (285, 672, 440, 812),
    "wordmark": (708, 852, 222, 1014),
    "arabic": (866, 955, 244, 1010),
    "tagline": (976, 1010, 186, 1038),
}

def trace(y0, y1, x0, x1, threshold=170):
    region = dark[y0:y1, x0:x1]
    bmp = potrace.Bitmap(region <= threshold)
    path = bmp.trace(turdsize=6, alphamax=1.0, opticurve=True, opttolerance=0.2)
    d = []
    for curve in path:
        sp = curve.start_point
        d.append(f"M{sp.x:.1f} {sp.y:.1f}")
        for seg in curve.segments:
            if seg.is_corner:
                d.append(f"L{seg.c.x:.1f} {seg.c.y:.1f}L{seg.end_point.x:.1f} {seg.end_point.y:.1f}")
            else:
                d.append(f"C{seg.c1.x:.1f} {seg.c1.y:.1f} {seg.c2.x:.1f} {seg.c2.y:.1f} {seg.end_point.x:.1f} {seg.end_point.y:.1f}")
        d.append("Z")
    return "".join(d), x1 - x0, y1 - y0

def svg(d, w, h, fill="currentColor"):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">'
            f'<path fill="{fill}" fill-rule="evenodd" d="{d}"/></svg>')

os.makedirs(OUT, exist_ok=True)
paths = {}
for name, (y0, y1, x0, x1) in BANDS.items():
    d, w, h = trace(y0, y1, x0, x1)
    paths[name] = (d, w, h, x0, y0)
    with open(os.path.join(OUT, f"invtra-{name}.svg"), "w") as f:
        f.write(svg(d, w, h, COLOR))

# Full lock-up (all bands in their original positions)
x0 = min(v[3] for v in paths.values()); y0 = min(v[4] for v in paths.values())
x1 = max(v[3] + v[1] for v in paths.values()); y1 = max(v[4] + v[2] for v in paths.values())
groups = "".join(f'<path transform="translate({v[3]-x0} {v[4]-y0})" fill-rule="evenodd" d="{v[0]}"/>' for v in paths.values())
with open(os.path.join(OUT, "invtra-logo.svg"), "w") as f:
    f.write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {x1-x0} {y1-y0}" fill="{COLOR}">{groups}</svg>')

# Paths as a TS module so React components can inline the logo (themeable via currentColor)
ts = ["// Generated by scripts/vectorize-logo.py from the official raster logo. Do not edit by hand.\n"]
for name, (d, w, h, _, _) in paths.items():
    ts.append(f'export const {name.upper()}_PATH = "{d}";\nexport const {name.upper()}_VIEWBOX = "0 0 {w} {h}";\n')
os.makedirs(os.path.join(ROOT, "src", "lib", "brand"), exist_ok=True)
with open(os.path.join(ROOT, "src", "lib", "brand", "logo-paths.ts"), "w") as f:
    f.write("\n".join(ts))

# Raster icons: the mark centred on ivory
mark = src.crop((440, 285, 812, 672))
for size, name in [(512, "icon-512.png"), (192, "icon-192.png"), (180, "apple-icon.png"), (48, "favicon-48.png")]:
    canvas = Image.new("RGBA", (size, size), (250, 247, 242, 255))
    m = mark.copy()
    m.thumbnail((int(size * 0.72), int(size * 0.72)), Image.LANCZOS)
    canvas.alpha_composite(m, ((size - m.width) // 2, (size - m.height) // 2))
    canvas.convert("RGB").save(os.path.join(OUT, name), optimize=True)
print("done")
